version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.1
jobs:
  test:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:11.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    steps:
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - node/install-packages:
          cache-path: ~/rentx/node_modules
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  test:
    jobs:
      - test
