name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: 'http://localhost:3333'
      PORT: '3333'
      RESET_PASSWORD_URL: 'http://localhost:3333/v1/password/reset?token='
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_TIME: '15m'
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      REFRESH_TOKEN_EXPIRATION_DAYS: '30'
      DB_HOST: 'localhost'
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_HOST: 'localhost'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: ''
      STORAGE_DRIVER: 'local'
      MAIL_DRIVER: 'ethereal'
      MAIL_SENDER: ${{ secrets.MAIL_SENDER }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2

      - name: Configure typeorm
        run: cp ormconfig.example.js ormconfig.js

      - name: Run tests and coverage
        run: |
          npm install
          npm run test

      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage/
